# Solux OS — Módulo de particionado (Calamares)
# Cifrado LUKS activado por defecto para máxima seguridad.
---
efiSystemPartition: "/boot/efi"
userSwapChoices:
    - none
    - small
    - suspend

drawNestedPartitions: false
alwaysShowPartitionLabels: true

initialPartitioningChoice: erase
initialSwapChoice: suspend

# Cifrado por defecto
defaultFileSystemType: "ext4"
enableLuksAutomatedPartitioning: true
luksGeneration: luks2

# Requerir passphrase fuerte para LUKS
requiredStorage: 20.0
