#
# Solux OS — Pantalla de login (LightDM GTK Greeter)
# © 2026 Pollocrudo Company
#
[greeter]
# Fondo de marca
background = /usr/share/backgrounds/solux/default.jpg
user-background = false
# Tema e iconos Solux
theme-name = SoluxOS-Dark
icon-theme-name = Solux-Icons
# Tipografía
font-name = Inter 11
xft-antialias = true
xft-hintstyle = hintslight
xft-rgba = rgb
# Logo en el recuadro de login
default-user-image = /usr/share/pixmaps/solux/solux-logo.png
# Reloj centrado arriba
clock-format = %A, %d de %B — %H:%M
indicators = ~host;~spacer;~clock;~spacer;~language;~session;~power
# Posición del recuadro de login (centro)
position = 50%,center 50%,center
# Sin lista de teclado innecesaria
keyboard =
reader =
